version: '3'
services:
    mariadb:
        container_name: mariadb
        image: mariadb
        networks:
            - inception
        env_file: .env
        build:
            args:
                SQL_DATABASE: $SQL_DATABASE
                SQL_USER: $SQL_USER
                SQL_PASSWORD: $SQL_PASSWORD
                SQL_ROOT_PASSWORD: $SQL_ROOT_PASSWORD
            context: requirements/mariadb
            dockerfile: Dockerfile
        volumes:
            - mariadb:/var/lib/mysql
        restart: always
        expose:
            - "3306"

    nginx:
        container_name: nginx
        image: nginx
        volumes:
            - wordpress:/var/www/wordpress
        networks:
            - inception
        depends_on:
            - wordpress
        build:
            context: requirements/nginx
            dockerfile: Dockerfile
        env_file: .env
        ports:
            - "443:443"
        restart: on-failure

    wordpress:
        container_name: wordpress
        image: wordpress
        env_file: .env
        volumes:
            - wordpress:/var/www/wordpress
        networks:
            - inception
        build:
            context: requirements/wordpress
            dockerfile: Dockerfile
        depends_on:
            - mariadb
        restart: on-failure
        expose:
            - "9000"

networks:
    inception:
        driver: bridge

volumes:
    wordpress:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/Users/hferraud/data/wordpress'
    mariadb:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/Users/hferraud/data/mariadb'